[project]
name = "Projektarbeit-Streamlit"
version = "0.1.0"
description = "Add a short description here"
authors = ["XhenZui <64024277+XhenZui@users.noreply.github.com>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]

[dependencies]
python = ">=3.12.7,<4"
streamlit = ">=1.39.0,<2"
pandas = ">=2.2.3,<3"
numpy = ">=1.26.4,<2"
streamlit-folium = ">=0.23.0,<0.24"
requests = ">=2.32.3,<3"
